#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/mnt/ubifs
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel


#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
hostname -F /etc/sysconfig/HOSTNAME

mount -n -t proc none /proc
mount -n -t sysfs none /sys
mount -n -t usbfs none /proc/bus/usb
mount -t ramfs none /dev

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s

# mounting file system specified in /etc/fstab
mkdir -p /dev/pts
mkdir -p /dev/shm
mount -n -t devpts none /dev/pts -o mode=0622
mount -n -t tmpfs tmpfs /dev/shm
mount -n -t ramfs none /tmp
mount -n -t ramfs none /var
mkdir -p /var/empty
mkdir -p /var/log
mkdir -p /var/lock
mkdir -p /var/run
mkdir -p /var/tmp

hwclock -s

syslogd

/etc/rc.d/init.d/netd start
free_arp &
if [ ! -e /dev/ubi0 ] ; then
	ubiattach /dev/ubi_ctrl -m 4
fi
if [ ! -e /dev/ubi0_0 ] ; then
	ubimkvol /dev/ubi0 -s 85MiB -N app
fi
# mount -t ubifs ubi0:app /mnt/ubifs


if [ -f /mnt/ubifs/user-init ] ; then
	/mnt/ubifs/user-init
fi

ifconfig lo 127.0.0.1
/etc/init.d/ifconfig-eth0


